### PR TITLE
rename libhostspriv.so to libuserhosts.so

### PR DESCRIPTION
**Pull request by bobvanderlinden**
I'd like to package hosts/libhostspriv.so for [Nix](https://nixos.org/). I ran into this project due to https://discourse.nixos.org/t/change-etc-hosts-using-shell-nix/9335/13 and I think it can help out quite a bit for Nix users.

However, the naming is a bit confusing. I'm not sure I can introduce a package called `hosts`. In addition, `libhostspriv.so` is named differently, which can be confusing.

That's why I'd like to suggest renaming the project from hosts/libhostspriv.so to userhosts/libuserhosts.so. I can totally understand if this is unwanted. But I thought I'd suggest it before creating the actual package. Let me know what you think.

I also added support to do `make install` so that packaging will likely be straightforward.

### CODE REVIEW

**Review by figiel — APPROVED** [review]

**Comment by figiel** [comment]
I'm fine with the change.

**Comment by bobvanderlinden** [comment]
Thanks for merging! 😄👍 Could you create a version tag so that I can use that version for the package of userhosts?

**Comment by figiel** [comment]
Done, it's v1.0.0.

**Comment by bobvanderlinden** [comment]
Thanks! Created a PR to add it to nixpkgs: https://github.com/NixOS/nixpkgs/pull/130045

**Pull request merged**
